CREATE DATABASE receitas;

USE receitas;

CREATE TABLE recipes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    ingredientes TEXT NOT NULL
);

-- Exemplos de receitas
INSERT INTO recipes (nome, ingredientes)
VALUES 
('Pizza Margherita', 'tomate, queijo, manjericão'),
('Sanduíche de Queijo', 'pão, queijo, presunto'),
('Salada Caprese', 'tomate, queijo, manjericão, azeite'),
('Panqueca Americana', 'farinha, leite, ovo, açúcar, fermento, manteiga'),
('Frango Xadrez', 'frango, pimentão verde, pimentão vermelho, cebola, molho shoyu, amendoim'),
('Feijoada', 'feijão preto, carne seca, linguiça, lombo de porco, bacon, alho, cebola'),
('Lasanha de Carne', 'massa de lasanha, carne moída, molho de tomate, queijo mussarela, queijo parmesão, creme de leite'),
('Sopa de Legumes', 'batata, cenoura, chuchu, abobrinha, cebola, alho, caldo de legumes'),
('Strogonoff de Frango', 'frango, creme de leite, molho de tomate, ketchup, mostarda, champignon'),
('Risoto de Camarão', 'arroz arbóreo, camarão, vinho branco, cebola, alho, caldo de legumes, queijo parmesão'),
('Torta de Limão', 'bolacha maria, manteiga, leite condensado, creme de leite, limão'),
('Brigadeiro', 'leite condensado, achocolatado, manteiga, chocolate granulado'),
('Hambúrguer Artesanal', 'carne moída, pão de hambúrguer, queijo cheddar, tomate, alface, maionese'),
('Omelete Simples', 'ovo, sal, queijo, presunto'),
('Bolo de Cenoura', 'cenoura, farinha, açúcar, chocolate, manteiga, fermento'),
('Pizza de Calabresa', 'calabresa, queijo, molho de tomate, cebola, orégano'),
('Coxinha de Frango', 'frango, farinha, manteiga, leite, caldo de galinha'),
('Pão de Alho', 'pão, alho, manteiga, queijo, salsinha'),
('Macarrão ao Alho e Óleo', 'macarrão, alho, azeite, salsinha'),
('Salmão Grelhado', 'salmão, azeite, limão, sal, pimenta'),
('Moqueca de Peixe', 'peixe, leite de coco, azeite de dendê, pimentão, cebola, tomate, coentro'),
('Arroz à Grega', 'arroz, cenoura, ervilha, uva-passa, pimentão, milho'),
('Pastel de Queijo', 'massa de pastel, queijo, orégano'),
('Pudim de Leite Condensado', 'leite condensado, leite, ovo, açúcar'),
('Churrasco Tradicional', 'carne, sal grosso'),
('Espaguete à Carbonara', 'macarrão, ovo, bacon, queijo parmesão, pimenta-do-reino'),
('Tacos Mexicanos', 'tortilla, carne moída, alface, tomate, queijo, molho picante'),
('Ceviche', 'peixe branco, limão, cebola roxa, coentro, pimenta'),
('Quiche de Espinafre', 'espinafre, ovo, creme de leite, queijo, massa'),
('Batata Recheada', 'batata, queijo, bacon, creme de leite, cebolinha'),
('Panqueca de Frango', 'massa de panqueca, frango desfiado, molho de tomate, queijo'),
('Caldo Verde', 'batata, couve, linguiça, alho, azeite'),
('Fondue de Queijo', 'queijo, vinho branco, pão, alho'),
('Cachorro-Quente', 'pão, salsicha, molho de tomate, batata palha'),
('Risoto de Cogumelos', 'arroz arbóreo, cogumelos, vinho branco, queijo parmesão, caldo de legumes'),
('Pão de Queijo', 'polvilho azedo, queijo, leite, ovo, óleo'),
('Sushi', 'arroz japonês, peixe cru, alga nori, vinagre de arroz'),
('Escondidinho de Carne', 'carne moída, purê de batata, queijo, molho de tomate'),
('Wrap de Frango', 'tortilla, frango, alface, tomate, maionese'),
('Torta de Frango', 'massa de torta, frango desfiado, requeijão, milho, ervilha'),
('Cuscuz Nordestino', 'flocos de milho, água, sal, manteiga'),
('Camarão na Moranga', 'camarão, abóbora, creme de leite, queijo, tomate'),
('Baião de Dois', 'arroz, feijão, carne seca, queijo coalho, manteiga de garrafa'),
('Tapioca com Coco', 'goma de tapioca, coco ralado, leite condensado'),
('Frango à Parmegiana', 'frango, molho de tomate, queijo, farinha de rosca, ovo'),
('Lentilha Refogada', 'lentilha, cebola, alho, azeite, cenoura'),
('Kibe Assado', 'carne moída, trigo para kibe, cebola, hortelã, azeite'),
('Chili com Carne', 'carne moída, feijão vermelho, pimentão, tomate, pimenta'),
('Bolinho de Bacalhau', 'bacalhau, batata, ovo, farinha, salsinha'),
('Ratatouille', 'berinjela, abobrinha, tomate, pimentão, alho, azeite'),
('Pavê de Chocolate', 'biscoito champanhe, creme de chocolate, creme de leite, chocolate granulado'),
('Sorvete de Morango', 'morango, creme de leite, leite condensado'),
('Torta de Maçã', 'massa de torta, maçã, açúcar, canela, manteiga'),
('Frango Assado com Batatas', 'frango, batata, azeite, alho, alecrim'),
('Polenta com Molho', 'fubá, água, molho de tomate, carne moída, queijo parmesão'),
('Cuscuz Paulista', 'farinha de milho, peixe, tomate, ervilha, ovo'),
('Bolacha de Amendoim', 'amendoim, açúcar, ovo, manteiga'),
('Abobrinha Recheada', 'abobrinha, carne moída, tomate, queijo, cebola'),
('Chá Gelado', 'chá preto, limão, açúcar, gelo'),
('Vitamina de Frutas', 'leite, banana, maçã, aveia'),
('Pizza de Quatro Queijos', 'queijo mussarela, queijo parmesão, queijo gorgonzola, queijo provolone, molho de tomate'),
('Lasanha de Berinjela', 'berinjela, molho de tomate, queijo, carne moída'),
('Torta de Banana', 'banana, açúcar, farinha, manteiga, canela'),
('Frango ao Curry', 'frango, leite de coco, curry, cebola, alho'),
('Bolo de Chocolate', 'farinha, açúcar, chocolate em pó, manteiga, ovo, fermento');
